name: CI

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**' # Ignore tags created by releases
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  checks: write
  id-token: write # needed for npm publish with provenance
  contents: write # needed for github release
  pull-requests: write # needed for coverage comment

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: zirkelc/setup-and-install@v1

      - name: Lint
        run: pnpm lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: zirkelc/setup-and-install@v1
        with:
          node-version: ${{ matrix.version }}

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:unit

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: zirkelc/setup-and-install@v1

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:unit --coverage

      - name: Coverage
        if: ${{ steps.install.conclusion == 'success' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: vitest.config.unit.ts

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: zirkelc/setup-and-install@v1

      - name: Build
        run: pnpm build

      - name: Deploy
        working-directory: test/aws
        run: pnpm run deploy

      - name: Test
        run: pnpm test:e2e

  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup and Install
        id: install
        uses: zirkelc/setup-and-install@v1
        with:
          node-version: 20

      - name: Build
        run: pnpm build

      - name: Publish Preview
        run: npx pkg-pr-new publish --pnpm --packageManager=pnpm
