name: CI

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: ./.github/actions/setup-and-install

      - name: Lint
        run: |
          pnpm lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v3

      - name: Setup and Install
        id: install
        uses: ./.github/actions/setup-and-install
        with:
          node-version: ${{ matrix.version }}

      - name: Build
        run: |
          pnpm build

      - name: Tests
        run: |
          pnpm test
