name: "CI"

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        id: install
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        id: install
        run: |
          npm ci

      - name: Tests
        run: |
          npm run test
