name: Release

on:
  push:
    branches:
      - "main"
    paths:
      - package.json

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: ./.github/actions/setup-and-install

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
          provenance: true

      - name: Post publish
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }} tag: ${{ steps.publish.outputs.tag }}"

      - name: Publish skipped
        if: steps.publish.outputs.type == 'none'
        run: |
          echo "Version in package.json has not changed. Skipping."
          exit 0


      - name: Draft Release
        if: steps.publish.outputs.type != 'none'
        id: draft-release
        uses: ncipollo/release-action@v1 # https://github.com/ncipollo/release-action
        with:
          allowUpdates: true
          generateReleaseNotes: true
          # body: ${{ steps.bump-version.outputs.changelog }}
          commit: ${{ github.sha }}
          draft: true
          name: ${{ steps.publish.outputs.tag }}
          tag: ${{ steps.publish.outputs.tag }}
